name: 'Map Github Username to Slack Id'
description: 'Accepts a GH Username, an inline JSON mapping of GH usernames to Slack ID's, and returns the desired slack id'
inputs: 
  github-username:  
    description: 'Github username' 
    required: true
  file:
    description: 'inline JSON mapping to parse'
    required: true
outputs:
  slack-id: # id of output
    description: 'Slack id'
runs:
  using: 'node12'
  main: 'index.js'
